### ISSUE TITLE
09-langauge-understanding-app.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.de-de#2]
Compound misspelled.

Current Translation (If its  a translation issue)
Eine
Vorhersage
ressource, mit der Sie Ihre Language Understanding-App veröffentlichen und Anforderungen vonClientanwendungen verarbeiten, die diese verwenden.

Suggested Translation (if it’s a translation issue)*
Eine
Vorhersageressource, mit der Sie Ihre Language Understanding-App veröffentlichen und Anforderungen vonClientanwendungen verarbeiten, die diese verwenden.
[09-language-understanding-app.md](https://github.com/MicrosoftLearning/AI-102-AIEngineer.de-de/files/7745127/09-language-understanding-app.md)

**Comment by olprod** [comment]
fixed.
![image](https://user-images.githubusercontent.com/16075726/149741990-ecee62b7-d4b4-4029-b8c0-534857f82996.png)
