### ISSUE TITLE
11-language-understanding-speech.md

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.de-de#3]
English letter "Y" for Year instead of German letter "J" for Jahr. Space missing in "Formatzu".

Current Translation (If its  a translation issue)
Möglicherweise haben Sie Probleme beim Erkennender
GetDay
-Absicht mit einer bestimmten Datumsentität, da es schwierig ist, ein Datum im
MM/TT/YYYY
-Formatzu verbalisieren.

Suggested Translation (if it’s a translation issue)*
Möglicherweise haben Sie Probleme beim Erkennender
GetDay
-Absicht mit einer bestimmten Datumsentität, da es schwierig ist, ein Datum im
MM/TT/JJJJ
-Format zu verbalisieren.
[11-language-understanding-speech.md](https://github.com/MicrosoftLearning/AI-102-AIEngineer.de-de/files/7745135/11-language-understanding-speech.md)

**Comment by olprod** [comment]
fixed.
![image](https://user-images.githubusercontent.com/16075726/149742148-e992e25b-3b9e-43a9-9792-6fa556f858d4.png)
